// Code generated by "stringer -type=direction"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dirUp-0]
	_ = x[dirDown-1]
	_ = x[dirLeft-2]
	_ = x[dirRight-3]
}

const _direction_name = "dirUpdirDowndirLeftdirRight"

var _direction_index = [...]uint8{0, 5, 12, 19, 27}

func (i direction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_direction_index)-1 {
		return "direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _direction_name[_direction_index[idx]:_direction_index[idx+1]]
}
